local-patch (0.17) unstable; urgency=medium
  * Trigger may be called for deleted file, do not throw an error
  * Gracefully handle absent files in postinst and prerm

 -- Denis Bychkov <manover@gmail.com>  Wed, 12 Jul 2017 12:21:08 -0400

diff --git a/debian/local-patch.postinst.in b/debian/local-patch.postinst.in
--- a/debian/local-patch.postinst.in
+++ b/debian/local-patch.postinst.in
@@ -5,16 +5,22 @@ PKG=#PACKAGE#
 
 case $1 in
 configure|reconfigure)
-	for p in ${index[@]}; do
-		patch_file <${PDIR}/$p
+	for f in ${!index[@]}; do
+		[ ! -f "$f" ] && continue;
+		p="${PDIR}/${index[$f]}"
+		if [ ! -f "$p" ]; then
+			echo "#PACKAGE#: bad index file, unable to find $p (patch for $f)" >&2
+		else
+			patch_file <$p
+		fi
 	done
 	;;
 triggered)
 	shift
 	for f in $@; do
 		if [ ! -f "$f" ]; then
-			echo "#PACKAGE#: trigger called for non-existing file $f" >&2
-			exit 1
+			echo "#PACKAGE#: skipping deleted file $f" >&2
+			continue
 		fi
 		p=${index[$f]}
 		#printf "#PACKAGE#: file %s, patches: %s\n" "$f" "$pl" >&2
